SELECT * FROM STUDENT;

INSERT INTO STUDENT(NAME, EMAIL, PHONE_NUMBER)
VALUES('VISHAL BABAR', 'VISHALBABAR7351@GMAIL.COM', 8999528919);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Aarav Sharma', 'aarav.sharma@gmail.com', 9876543210);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Priya Patel', 'priya.patel@yahoo.com', 9823456789);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Rohan Verma', 'rohan.verma@rediffmail.com', 9988776655);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Ananya Singh', 'ananya.singh@gmail.com', 9765432109);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Vikram Reddy', 'vikram.reddy@outlook.com', 9654321098);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Sneha Gupta', 'sneha.gupta@gmail.com', 9543210987);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Arjun Kumar', 'arjun.kumar@yahoo.com', 9432109876);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Meera Joshi', 'meera.joshi@gmail.com', 9321098765);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Karan Malhotra', 'karan.malhotra@rediffmail.com', 9210987654);

INSERT INTO STUDENT (NAME, EMAIL, PHONE_NUMBER)
VALUES ('Divya Iyer', 'divya.iyer@gmail.com', 9109876543);

SELECT * FROM STUDENT;