SELECT * FROM STUDENT;

UPDATE STUDENT 
SET EMAIL = 'VISHALBABAR7351@GMAIL.COM'
WHERE ID = 1;

SELECT * FROM STUDENT ORDER BY ID ASC;

SELECT * FROM STUDENT ORDER BY ID DESC;

UPDATE STUDENT 
SET FULL_NAME = 'VISHAL'
WHERE AGE >= 30;

UPDATE STUDENT 
SET AGE = 30, CITY = 'MUMBAI'
WHERE ID = 3;

UPDATE STUDENT 
SET AGE = AGE + 1 
WHERE EMAIL LIKE '%@GMAIL.COM';