SELECT * FROM STUDENT;

-- RENAME COLUMN NAME ..................
ALTER TABLE STUDENT 
RENAME COLUMN FULL_NAME TO NAME;

-- CHANGE DATA TYPE ....................
ALTER TABLE STUDENT 
ALTER COLUMN name TYPE VARCHAR(50);

-- ADD CONSTRAINT TO COLUMN ..............
ALTER TABLE STUDENT 
ALTER COLUMN EMAIL SET NOT NULL;

ALTER TABLE STUDENT 
ADD CONSTRAINT AGE CHECK(AGE >= 30);  

-- DELATE COLUMN FROM TABLE
ALTER TABLE STUDENT 
DROP COLUMN EMAIL;

ALTER TABLE STUDENT 
ADD COLUMN EMAIL VARCHAR(100);

