SELECT * FROM STUDENT;

-- lOGICAL OPERATORS => AND, OR, NOT 

SELECT * FROM STUDENT
WHERE AGE >= 20 AND AGE <= 30
ORDER BY AGE ASC;

SELECT * FROM STUDENT 
WHERE (AGE >= 42) OR (FULL_NAME = 'ADITI');

SELECT * FROM STUDENT 
WHERE NOT (AGE >= 25)
ORDER BY ID ASC;
