SELECT * FROM STUDENT;

-- BETWEEN
SELECT * FROM STUDENT 
WHERE SALARY BETWEEN 5000 AND 50000;

-- LIKE
SELECT * FROM STUDENT 
WHERE EMAIL LIKE '%@GMAIL.COM';  

SELECT * FROM STUDENT 
WHERE EMAIL LIKE '%#gmail.com';

SELECT * FROM STUDENT 
WHERE FULL_NAME LIKE 'Dinesh%';

SELECT * FROM STUDENT 
WHERE FULL_NAME LIKE '%n%';

 -- IN OPERATORS
SELECT * FROM STUDENT 
WHERE SALARY IN (5000, 50000);

SELECT * FROM STUDENT 
WHERE DEPT_MENT IN ('CS', 'IT');

