SELECT * FROM DIV_A;

-- IS NULL
SELECT* FROM DIV_A 
WHERE EMAIL IS NULL;

-- ORDER BY
SELECT * FROM DIV_A ORDER BY ID DESC;
SELECT * FROM DIV_A ORDER BY ID ASC;

 -- LIMIT 
SELECT * FROM DIV_A 
LIMIT 3;
 
 -- DISTINCT
SELECT DISTINCT AGE 
FROM DIV_A;

SELECT COUNT (DISTINCT AGE) AS AGE_COUNT 
FROM DIV_A;
