SELECT * FROM DIV_A;
SELECT * FROM DIV_B;

-- UNION => COMBINE RESULTS AND REMOVE DULPICATE
SELECT * FROM DIV_A
UNION 
SELECT * FROM DIV_B;

-- UNION ALL => COMBINE RESULTS AND KEEP DULPICATE
SELECT * FROM DIV_A
UNION ALL
SELECT * FROM DIV_B;

-- INTERSECT => RETURN COMMON DATA IN BOTH TABLE  
SELECT * FROM DIV_A
INTERSECT
SELECT * FROM DIV_B;

-- EXCEPT => RETURN RESULT IN FIRST TABLE BUT NOT IN SECOND
SELECT * FROM DIV_A
EXCEPT
SELECT * FROM DIV_B;