SELECT * FROM STUDENTS;

-- STRING FUNCTION => UPPER, LOWER, REPLACE, SUBSTRING, TRIM, LTRIM, RTRIM, CONCAT, LENGTH

SELECT UPPER(full_name) as upper_case 
FROM STUDENTS;

SELECT LOWER(full_name) AS lower_case 
FROM Students;

SELECT * FROM Students 
WHERE full_name like 'A%';

SELECT * FROM Students 
WHERE full_name like '%A';

SELECT FULL_NAME, LENGTH(FULL_NAME) AS COUNT_CHAR
FROM STUDENTS;

SELECT FULL_NAME, REPLACE(FULL_NAME,' ', '_') AS NEW_NAME
FROM STUDENTS;

SELECT SUBSTRING(FULL_NAME, 1,4) AS FOUR_CHAR 
FROM STUDENTS;